#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
12_build_run_summary_placeholder.py

Purpose:
    Build a frontend-readable run_summary.json by combining selected pipeline outputs.
    This is a lightweight placeholder to connect the backend pipeline to the static frontend.

Example:
    python 12_build_run_summary_placeholder.py \
      --station SMA \
      --station-name "Zürich / Fluntern" \
      --target-state gwl2.0 \
      --capability-json outputs/capability_sma.json \
      --comparison-csv outputs/weather_comparison.csv \
      --output outputs/run_sma_gwl2/run_summary.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict

import pandas as pd


def read_json_optional(path: str | None) -> Dict[str, Any]:
    if not path:
        return {}
    p = Path(path)
    if not p.exists():
        return {}
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)


def read_metrics_optional(path: str | None) -> list[dict[str, Any]]:
    if not path:
        return []
    p = Path(path)
    if not p.exists():
        return []
    df = pd.read_csv(p)
    return df.to_dict(orient="records")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build frontend run_summary.json placeholder.")
    parser.add_argument("--station", default="SMA")
    parser.add_argument("--station-name", default="Zürich / Fluntern")
    parser.add_argument("--ref-state", default="ref91-20")
    parser.add_argument("--target-state", default="gwl2.0")
    parser.add_argument("--capability-json", default=None)
    parser.add_argument("--comparison-csv", default=None)
    parser.add_argument("--output", required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    capability = read_json_optional(args.capability_json)
    metrics = read_metrics_optional(args.comparison_csv)

    payload = {
        "run_id": f"{args.station.lower()}_{args.target_state}",
        "station": {
            "id": args.station,
            "name": args.station_name,
            "capability_level": capability.get("capability_level", "Unknown"),
            "capability_reason": capability.get("reason", "Capability metadata not provided."),
        },
        "scenario": {
            "ref_state": args.ref_state,
            "target_state": args.target_state,
            "selection_method": "FRY: FS over tas/hurs/rsds + official CH2025 tasmax/tasmin tie-break; XMY: profile-based stress selection",
        },
        "files": [],
        "sources": [
            {"name": "CH2025 DAILY-LOCAL", "description": "Future scenario signals by GWL", "url": "https://www.meteoswiss.admin.ch/"},
            {"name": "MeteoSwiss hourly observations", "description": "Historical hourly backbone", "url": "https://www.meteoswiss.admin.ch/"},
        ],
        "monthly_temperature": [],
        "monthly_radiation": [],
        "xmy_scores": [],
        "evaluation_metrics": metrics,
        "assumptions": [
            "This run summary was generated by a placeholder connector.",
            "Add real file manifests, monthly diagnostics and XMY ranking outputs when the pipeline is executed.",
        ],
    }

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
